server:
  port: 10003
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://nekotori.xyz:3306/dev?characterEncoding=utf8&characterSetResults=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234abcd@
mybatis:
  mapper-locations: classpath:xyz/nekotori/nekoweb/mapper/*.xml
  type-aliases-package: xyz.nekotori.nekoweb.entity
  configuration:
    cache-enabled: false